SELECT vtoi.id,
       vtoi.oi                               orderId,
       vtoi.dc                               drawCode,
       vtoi.tn                               ticketNumber,
       vtoi.pn                               pageNumber,
       vtoi.cn                               columnNumber,
       vtoi.sn                               sectionNumber,
       IF(vtoi.is_lo, CONCAT('Lo',vtoi.posts), vtoi.posts) posts,
       vtoi.post_analyze                     postAnalyze,
       vtoi.is_lo                            isLo,
       vtoi.multi_digit                      multiDigit,
       vtoi.bet_type                         betType,
       vtoi.bet_title                        betTitle,
       vtoi.rc                               rebateCode,
       vtoi.number_from                      numberFrom,
       vtoi.number_to                        numberTo,
       vtoi.number_three                     numberThree,
       vtoi.number_four                      numberFour,
       vtoi.number_detail                    numberDetail,
       vtoi.number_quantity                  numberQuantity,
       vtoi.cc                               currencyCode,
       vtoi.bet_amount                       betAmount,
       vtoi.total_amount                     totalAmount,
       vtoi.mc                               memberCode,
       vtoi.member_share                     share,
       vtoi.member_commission                commission,
       vtoi.member_water_rate                waterRate,
       vtoi.member_rebate_rate               rebateRate,
       vtoi.status
FROM PREFIX_order_items vtoi
INNER JOIN PREFIX_orders o ON vtoi.oi = o.id AND o.status = 1
WHERE vtoi.dc = :drawCode
