server:
  port: 7002
  max-http-header-size: 65536

spring:
  application:
    name: system-service
  profile: ${PROFILE:local}

  hazelcast:
    cluster-name: qa #${CLUSTER_NAME}
    member-list: 3.0.132.125:5702 #${MEMBER_LIST}

  # database setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vnone?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: rdsadmin
    password: password
    hikari:
      connectionTimeout: 60000
      initializationFailTimeout: 3000
      connectionTestQuery: SELECT 1
      validationTimeout: 60000
      maxLifetime: 35000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 30000
      registerMbeans: false
      poolName: system-connection-pool
      isolate-internal-queries: true

  jpa:
    hibernate:
      ddl-auto: none

  AWS_CONFIG:
    REGION: ${REGION:ap-southeast-1}
    BUCKET: ${BUCKET:asia}
    KEY: ${KEY:key}
    SECRET: ${SECRET:secret}
    VISIBILITY: public
    URL:
      BASE: s3.amazonaws.com

  security:
    OAUTH2:
      CLIENT_ID: LotteryV2@123
      CLIENT_SECRET: LotteryV2@123@#2%9999^&$

    JWT_KEY: GeNius@LeAP123!@#

springdoc:
  packages-to-scan: com.hacknovation.systemservice.v3_0_0.controller,com.hacknovation.systemservice.v1_0_0.ui.controller.swagger
  swagger-ui:
    persist-authorization: true
    operations-sorter: method

native-query:
  package-scan: com.hacknovation.systemservice
  file:
    sufix: sql